---
meeting_start_hour: 18
meeting_end_hour: 20
input_path: "<<path to input files here>>"
output_path: "<<path to output files here>>"
cpe_template_path: "<<path to cpe template file here>>"
chapter_name: "(ISC)2 - Silicon Valley Chapter"
chapter-officers:
  Test_Officer:
    email: "officer@somthing.org"
    user_name: "Some Officer"
    member_first_name: "Some"
    member_last_name: "Officer"
    member_certification_id: "536176"
    personal_email: "me@gmail.com"
    phone_number: "None"

# Google Configuration Values
# ================================
# ID of google sheet to store metrics
metrics_sheet_id: "some value here"
# Folder to store CPE files
cpe_folder_id: "some value here"
# Folder where Atttendee Report files are stored
attendee_report_folder_id: "some value here"